<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="RED-WING" failures="1" tests="1" name="Default test" time="14.455" errors="0" timestamp="2025-03-25T03:00:18 IST">
  <testcase classname="tests.UI_Tests" name="testToIntearctWithCategoriesDropdown" time="2.809">
    <failure type="java.lang.AssertionError" message="POWER TOOLS CATEGORY VLIDATED expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: POWER TOOLS CATEGORY VLIDATED expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at tests.UI_Tests.testToIntearctWithCategoriesDropdown(UI_Tests.java:54)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:569)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testToIntearctWithCategoriesDropdown -->
  <testcase classname="tests.UI_Tests" name="testCountPlierTypes" time="0.0">
    <ignored/>
  </testcase> <!-- testCountPlierTypes -->
  <testcase classname="tests.UI_Tests" name="testOpenPlierInfo" time="0.0">
    <ignored/>
  </testcase> <!-- testOpenPlierInfo -->
  <testcase classname="tests.UI_Tests" name="htmlTableTest" time="0.0">
    <ignored/>
  </testcase> <!-- htmlTableTest -->
  <testcase classname="tests.UI_Tests" name="testToInteractWithCheckBox" time="0.0">
    <ignored/>
  </testcase> <!-- testToInteractWithCheckBox -->
</testsuite> <!-- Default test -->
